#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd steadystate
runApplication blockMesh
runApplication checkMesh
runApplication renumberMesh -overwrite
runApplication rhoDarcyFoam

cp system/blockMeshDict ../transient/system/
cp 1/p ../transient/0/
cp 1/p_rgh ../transient/0/
cp 1/U ../transient/0/U
cp 0/K ../transient/0/K

cd ..

cd transient
runApplication blockMesh
runApplication renumberMesh -overwrite
runApplication rhoDarcyFoam

cd ..
