#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf dynamicCode
rm -f log.* 0/h 0/theta 0/C 0/Utheta
rm -rf 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* constant/polyMesh
rm -f *Balance.csv
