#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd steadystate
runApplication blockMesh
runApplication renumberMesh -overwrite
runApplication checkMesh
runApplication setRandomField
runApplication rhoDarcyFoam

cp system/blockMeshDict ../transient/system/

cd ..

cd transient
runApplication blockMesh
runApplication renumberMesh -overwrite

cp ../steadystate/1/p     ../transient/0/
cp ../steadystate/1/p_rgh ../transient/0/
cp ../steadystate/1/U     ../transient/0/U
cp ../steadystate/1/K     ../transient/0/K

#runApplication checkMesh
runApplication rhoDarcyFoam

cd ..
